CREATE DATABASE reslib;
USE reslib;

CREATE TABLE `rs_correct_resources` (
    `id` INT NOT NULL,
    `str_id` VARCHAR(100) NOT NULL,
    `title` VARCHAR(1000) NOT NULL,
    `all_title` VARCHAR(2000) NULL,
    `series_titles` VARCHAR(1000) NULL,
    `author` VARCHAR(1000) NULL,
    `author_intro` TEXT NULL,
    `editor` VARCHAR(1000) NULL,
    `publish` VARCHAR(1000) NULL,
    `publish_time` TIMESTAMP NULL,
    `publish_place` VARCHAR(1000) NULL,
    `catalogue` TEXT NULL,
    `preface` TEXT NULL,
    `content_intro` TEXT NULL,
    `abstracts` TEXT NULL,
    `ISBN` VARCHAR(100) NULL,
    `language` VARCHAR(50) NULL,
    `keyword` VARCHAR(500) NULL,
    `document_type` VARCHAR(100) NULL,
    `subcategory` VARCHAR(100) NULL,
    `product_features` VARCHAR(1000) NULL,
    `price` DECIMAL(8,2) NULL,
    `evaluation_number` INT NULL,
    `People_buy` INT NULL,
    `sellers_number` INT NULL,
    `packages` VARCHAR(100) NULL,
    `brand` VARCHAR(50) NULL,
    `product_code` VARCHAR(50) NULL,
    `is_set` VARCHAR(10) NULL,
    `format` VARCHAR(50) NULL,
    `paper` VARCHAR(50) NULL,
    `collection_information` VARCHAR(500) NULL,
    `editor_recommendations` TEXT NULL,
    `pages` INT NULL,
    `words` INT NULL,
    `edition` INT NULL,
    `version` VARCHAR(100) NULL,
    `additional_version` VARCHAR(200) NULL,
    `Illustration_url` TEXT NULL,
    `image_url` TEXT NULL,
    `page_url` TEXT NULL,
    `data_source` VARCHAR(50) NULL,
    `data_type` VARCHAR(10) NULL,
    `data_status` VARCHAR(255) NULL DEFAULT '0',
    `creator` VARCHAR(100) NULL,
    `create_time` TIMESTAMP NULL,
    `updater` VARCHAR(100) NULL,
    `update_time` TIMESTAMP NULL,
    `deleted` SMALLINT NULL DEFAULT 0,
    `tenant_id` BIGINT NULL,
    `may` BIGINT NULL,
    CONSTRAINT `rs_correct_resources_key` PRIMARY KEY (`id`)
);
