CREATE TABLE `rs_correct_resources` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(1000) NOT NULL,
  `all_title` varchar(2000) DEFAULT NULL,
  `series_titles` varchar(1000) DEFAULT NULL,
  `author` varchar(1000) DEFAULT NULL,
  `author_intro` text,
  `editor` varchar(1000) DEFAULT NULL,
  `publish` varchar(1000) DEFAULT NULL,
  `publish_time` timestamp NULL DEFAULT NULL,
  `publish_place` varchar(1000) DEFAULT NULL,
  `catalogue` text,
  `preface` text,
  `content_intro` text,
  `abstracts` text,
  `ISBN` varchar(100) DEFAULT NULL,
  `language` varchar(50) DEFAULT NULL,
  `keyword` varchar(500) DEFAULT NULL,
  `document_type` varchar(100) DEFAULT NULL,
  `subcategory` varchar(100) DEFAULT NULL,
  `product_features` varchar(1000) DEFAULT NULL,
  `price` decimal(8,2) DEFAULT NULL,
  `evaluation_number` int DEFAULT NULL,
  `People_buy` int DEFAULT NULL,
  `sellers_number` int DEFAULT NULL,
  `packages` varchar(100) DEFAULT NULL,
  `brand` varchar(50) DEFAULT NULL,
  `product_code` varchar(50) DEFAULT NULL,
  `is_set` varchar(10) DEFAULT NULL,
  `format` varchar(50) DEFAULT NULL,
  `paper` varchar(50) DEFAULT NULL,
  `collection_information` varchar(500) DEFAULT NULL,
  `editor_recommendations` text,
  `pages` int DEFAULT NULL,
  `words` int DEFAULT NULL,
  `edition` int DEFAULT NULL,
  `version` varchar(100) DEFAULT NULL,
  `additional_version` varchar(200) DEFAULT NULL,
  `Illustration_url` text,
  `image_url` text,
  `page_url` text,
  `data_source` varchar(50) DEFAULT NULL,
  `data_type` varchar(10) DEFAULT NULL,
  `data_status` varchar(1) DEFAULT '0',
  `creator` varchar(100) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `updater` varchar(100) DEFAULT NULL,
  `update_time` timestamp NULL DEFAULT NULL,
  `deleted` smallint DEFAULT '0',
  `tenant_id` bigint DEFAULT NULL,
  `may` bigint DEFAULT NULL,
  `book_type` varchar(50) DEFAULT NULL,
  `base64_url` longtext,
  `str_id` varchar(100) NOT NULL,
  `distribution_scope` varchar(50) DEFAULT NULL,
  `weight` int DEFAULT NULL,
  `CIP` varchar(100) DEFAULT NULL,
  `height` int DEFAULT NULL,
  `CLCI` varchar(100) DEFAULT NULL,
  `printing_date` timestamp NULL DEFAULT NULL,
  `out_edition` int DEFAULT NULL,
  `first_publish_time` timestamp NULL DEFAULT NULL,
  `printing_edition` int DEFAULT NULL,
  `length` int DEFAULT NULL,
  `width` int DEFAULT NULL,
  `target_audience` varchar(100) DEFAULT NULL,
  `book_medium` varchar(100) DEFAULT NULL,
  `use_paper` varchar(50) DEFAULT NULL,
  `is_phonetic` varchar(50) DEFAULT NULL,
  `photocopy_version` varchar(50) DEFAULT NULL,
  `publisher_country` varchar(50) DEFAULT NULL,
  `translator` varchar(100) DEFAULT NULL,
  `printing_sheet` decimal(10,5) DEFAULT NULL,
  `printing_num` int DEFAULT NULL COMMENT '印数',
  `freebie_quantity` varchar(100) DEFAULT NULL,
  `compiler` varchar(100) DEFAULT NULL,
  `drawer` varchar(100) DEFAULT NULL,
  `annotation` varchar(100) DEFAULT NULL,
  `binding` varchar(50) DEFAULT NULL,
  `oral_narration` varchar(50) DEFAULT NULL,
  `planner` varchar(50) DEFAULT NULL,
  `copyright_provider` varchar(100) DEFAULT NULL,
  `e_book_release_time` datetime DEFAULT NULL,
  `is_have_e_book` varchar(50) DEFAULT NULL,
  `copyright_number` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `str_id_unique` (`str_id`)
) ENGINE=InnoDB AUTO_INCREMENT=967 DEFAULT CHARSET=utf8mb3

