#可采集数据的网站配置
need_get_cites:
#  - name: dangdang                  # 当当网配置
#    incremental_interval_days: 2    # 增量数据间隔天数
#    full_interval_days: 30          # 全量数据间隔天数
#    max_retries: 50                 # 最大重复数（不启用，修改最大重复数无效）
#  - name: dangdang_Ebook            # 当当网电子书配置
#    incremental_interval_days: 2    # 增量数据间隔天数
#    full_interval_days: 30          # 全量数据间隔天数
#    max_retries: 50                 # 最大重复数（不启用，修改最大重复数无效）
#  - name: xhsd                      # 新华书店
#    incremental_interval_days: 1    # 增量数据间隔天数
#    full_interval_days: 7           # 全量数据间隔天数
#    max_retries: 50                 # 最大重复数
#  - name: rmwjssp                   # 人民网军事视频
#    incremental_interval_days: 3    # 增量数据间隔天数
#    full_interval_days: 30          # 全量数据间隔天数
#    max_retries: 50                 # 最大重复数
#  - name: rmwxzyjhsp                # 人民网习重要讲话视频
#    incremental_interval_days: 1    # 增量数据间隔天数
#    full_interval_days: 20          # 全量数据间隔天数
#    max_retries: 50                 # 最大重复数
#  - name: 81sp                      # 81视频
#    incremental_interval_days: 2    # 增量数据间隔天数
#    full_interval_days: 25          # 全量数据间隔天数
#    max_retries: 50                 # 最大重复数
  - name: dangshi                   # 党史
    incremental_interval_days: 2    # 增量数据间隔天数
    full_interval_days: 25          # 全量数据间隔天数
    max_retries: 50                 # 最大重复数（不启用，修改最大重复数无效）
  - name: jingdong                  # 京东
    incremental_interval_days: 3    # 增量数据间隔天数
    full_interval_days: 25          # 全量数据间隔天数
    max_retries: 50                 # 最大重复数（不启用，修改最大重复数无效）
  - name: jingdong_dvd              # 京东_音像
    incremental_interval_days: 3    # 增量数据间隔天数
    full_interval_days: 25          # 全量数据间隔天数
    max_retries: 50                 # 最大重复数（不启用，修改最大重复数无效）
  - name: kong_fu_zi                # 孔夫子
    incremental_interval_days: 1    # 增量数据间隔天数
    full_interval_days: 25          # 全量数据间隔天数
    max_retries: 50                 # 最大重复数（不启用，修改最大重复数无效）